apiVersion: v1
name: k8-automation
version: 0.1.0
description: A Helm chart for k8-automation
keywords:
  - kubernetes
  - atomist
home: https://github.com/atomist/k8-automation/blob/master/assets/helm/
maintainers:
  - name: Atomist
    email: docker@atomist.com
    url: https://github.com/atomist
icon: https://images.atomist.com/logo/atomist-color-mark-transparent-small.png
appVersion: 0.8.0
