apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "k8-automation.fullname" . }}
  labels:
    app: {{ template "k8-automation.name" . }}
    chart: {{ template "k8-automation.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: {{ toJson .Values.config | squote }}
