dist: trusty
sudo: required
services:
- docker
language: node_js
node_js:
- 9.5.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-.*\\d+$/"
env:
  global:
  - ATOMIST_TEAM=T29E48P34
  - NPM_PUBLISH=true
  - NPM_REGISTRY=https://atomist.jfrog.io/atomist/api/npm/npm-dev-local
  - secure: JTKX9Cvqy0Rp1Q69H0YbQwsC8DHdKiQ1y9xeCsj6wkg9g4AtDepndPRgCCwhh6IPl+O+p0pdn88lvk3VeApxxZPCTcNA2+vi+ov87nVAl9gYZmO5j3WNwXJPbomMceq0ld2Xbp2rf8EiRqccSAI2ti3cZvT21O0llda31JKtKgW/9W6DMpRHpBQTVzizONMkeIqCZ7RxC39GLBjYt5ArP1aQYpueL1TZwZOInkCifFfWZyOIuAH5fcGIY5N1tO8VMyCK4/oAcuV7MtyEAx6BZtTsFpE3DeiTR81EO6FVML/5q0JWpNnHMxfBRQ4L6E6jPQEBeKxncRZfWzvJWaSSAhT5XBNiATY5eV7RluRGDg6NqUTHRKCL4wFTTfrCqTMkGBtZsM4evXZChmYrPoKXyfxxhxhooUYO2ywWld3BRYPFH9B0GuBnYdC7wDDQYhHQhV7ki14lUAFrqbvl7l9qP0l4R8fcN9kRZvqjmhYPy4S6LWjHcgIj+1s4eewG/Vyctx+a0NIrFn1ZicNpoWTq1k+UtPAOuxUHyMi1m3ByussU06HLzZ6WDb2YS1jpIcd1y0BmuGDOKoJG4g7db/ye8ZC4Eel4+TSRHlVQrWUAsWUIZW4K8S7x7FoYpumFgIU0IMt7v/Oho9nNCgL7B5XvbRxAVNnEWhlMKVlhdkSbw08=
  - DOCKER_REGISTRY=atomist
  - DOCKER_USER=atomist
  - secure: FZQxaJ8HNgtnoC3S0rrQDG3B8JJ59hc6YNVTLKDTp+IopGpNkCbI42lmriZYx5Rnv9ihipWlIzBzDR+9kPaZXDqrIm2Lzk6HzDkStCqKMj3wu3yhkR4U4T1PUzQsiGLmXkWgwIyOMg+SFoTWdwORSUo5JGnE7jrAnxGLeAuQPk8vMNYB0Vbh82eMo+Fz3ZqSOW8D+y027bPshvtuQMU88l9bSpJ+UcXvMPFWZO20ttj7JkpAYiBZsQS5JqeYWhOt7QgxCDjOZy+ry1z4VWRnl1t4739BS4plGf3uTq2UZkC8u2t6VFBySbrWbnmGA2Jv8sUL6xe9ZgrPjVp/ybyQOS60u1XC5lTa8xjz8TdvzPdkBCRXDdqnrZkxzb2HRZaYyzOoYA7SdybC8Lixc+ySWbCb03RmdjFqWuls4hEMSCNkCfyFf32gCED6UYASSiBEY7FsgVMl3fK6WQe9zDqbDdkcuwwWfrGEWZxHPaI6VulXZUku5BFjn92IrAfnMvJPqSlna1cEQpprvvLJONm4es+aXl/l/cTSNjfVDYamQXFyuq5GN1IVQPZDTAdSzXBxs6/4oxMVwh+WwDvXGKbKVRnrOcL8RhVbFPD7qP88V66VeD2Ha8uu7QBoZtE0HRl5sdUQYqWXreoaxpm1eGk93HY7FXA964gPXMMHH2sd86I=
before_install:
- openssl aes-256-cbc -K $encrypted_a057ff6950bc_key -iv $encrypted_a057ff6950bc_iv
  -in .npmrc.enc -out .npmrc -d
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
before_deploy:
- touch build/typedoc/.nojekyll
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build/typedoc
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
- provider: releases
  api_key: "$GITHUB_TOKEN"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
